// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqbojkktebgfignvudjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxYm9qa2t0ZWJnZmlnbnZ1ZGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDY3ODQsImV4cCI6MjA1NzgyMjc4NH0.Agad0xMu7CGuZum5qt1_IyMg_rb1ywtA1ZFUyokvlaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);